### Agregar producto
POST http://localhost:5000/producto
Content-Type: application/json

{
  "id": 1,
  "nombre": "Laptop",
  "cantidad": 10
}

### Consultar producto
GET http://localhost:5000/producto/1

### Actualizar producto
PUT http://localhost:5000/producto/1
Content-Type: application/json

{
  "cantidad": 20
}